ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

reverseProxy:
  # Backend server configuration
  backends:
    - id: "backend1"
      url: ${BACKEND1_URL:-http://localhost:8081}
      weight: 3
      healthCheckPath: "/health"
    - id: "backend2"
      url: ${BACKEND2_URL:-http://localhost:8082}
      weight: 2
      healthCheckPath: "/health"
    - id: "backend3"
      url: ${BACKEND3_URL:-http://localhost:8083}
      weight: 1
      healthCheckPath: "/health"

  # Load balancing configuration
  loadBalancing:
    strategy: "round-robin"  # Options: round-robin, random, least-connections, weighted, consistent-hash
    sessionSticky: false
    sessionCookieName: "BACKEND_ID"

  # Circuit breaker configuration
  circuitBreaker:
    failureRateThreshold: 50  # Percentage
    waitDurationInOpenState: 60000  # Milliseconds
    ringBufferSizeInClosedState: 10
    ringBufferSizeInHalfOpenState: 5
    automaticTransitionFromOpenToHalfOpenEnabled: true

  # Security settings
  security:
    ssl:
      enabled: false
      keyStorePath: "keystore.jks"
      keyStorePassword: "password"
    ipFiltering:
      enabled: false
      whitelistOnly: true
      whitelist: ["127.0.0.1", "::1"]
      blacklist: []
    rateLimit:
      enabled: true
      limit: 100  # Requests per window
      window: 60  # Window in seconds

  # WebSocket configuration
  webSocket:
    enabled: true
    pingInterval: 30000  # Milliseconds
    timeout: 15000  # Milliseconds

  # Server-Sent Events (SSE) configuration
  sse:
    enabled: true
    reconnectTime: 3000  # Milliseconds - suggested reconnect time for clients
    eventBufferSize: 100  # Number of events to buffer
    heartbeatInterval: 15000  # Milliseconds - interval for sending heartbeat events